import { CartProvider } from '../app/context/Context';
import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";
import ChatBot from '@/app/components/ChatBot'
import Whatsapp from '@/app/components/Whatsapp'
import { Toaster } from '@/components/ui/toaster';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const galaxy = localFont({
  src: "./fonts/Galaxy Regular.otf",
  variable: "--font-galaxy",
  weight: "100 900",
});

const domine = localFont({
  src: "./fonts/Domine-VariableFont_wght.ttf",
  variable: "--font-domine",
  weight: "100 900",
});

const montserratMedium = localFont({
  src: "./fonts/Montserrat-Medium.ttf",
  variable: "--font-montserratMedium",
  weight: "100 900",
});

const montserratSemiBold = localFont({
  src: "./fonts/Montserrat-SemiBold.ttf",
  variable: "--font-montserratSemiBold",
  weight: "100 900",
});

const montserratRegular = localFont({
  src: "./fonts/Montserrat-Regular.ttf",
  variable: "--font-montserratRegular",
  weight: "100 900",
});

const merriweather = localFont({
  src: "./fonts/Merriweather-Regular.ttf",
  variable: "--font-merriweather",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Cleopatra | Shop Luxury Watches & Jewellery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${galaxy.variable} ${domine.variable} ${merriweather.variable} ${montserratMedium.variable} ${montserratRegular.variable} ${montserratSemiBold.variable} antialiased`}
      >
        <CartProvider>
            {children}
            <Toaster />
            <Whatsapp />
            <ChatBot />
        </CartProvider>
      </body>
    </html>
  );
}
