import localFont from "next/font/local";
import "./globals.css";
import { AppProvider } from "./context/Context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const PoppinsBold = localFont({
  src: "./fonts/Poppins-Bold.ttf",
  variable: "--font-poppins-bold",
  weight: "100 900",
});

const MontBold = localFont({
  src: "./fonts/Montserrat-Bold.ttf",
  variable: "--font-poppins-bold",
  weight: "100 900",
});

const MontMedium = localFont({
  src: "./fonts/Montserrat-Medium.ttf",
  variable: "--font-poppins-bold",
  weight: "100 900",
});

export const metadata = {
  title: "Cleopatra Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen bg-gray-50">
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
